/**
 * @file phase1.cpp
 * @brief Phase 1 implementation of the Multiprogramming Operating System (MOS).
 *
 * This program simulates a basic operating system capable of loading,
 * executing, and terminating user programs. It supports memory operations,
 * simple instruction execution, and supervisor services through MOS.
 */

#include <iostream>
#include <fstream>
using namespace std;

// Global memory and CPU registers

char M[100][4]; // Main memory (100 words of 4 characters)

char R[4];  // General-purpose register
char IR[4]; // Instruction register
int IC;     // Instruction counter / Instruction pointer
int C;      // Toggle register / Condition flag
int m;      // Memory pointer

int SI;          // Service interrupt
char buffer[41]; // Input buffer

// Execution statistics

int TTL = 0; // Total time limit
int TLL = 0; // Total line limit

// File streams

ifstream fin;
ofstream fout;

/**
 * Initializes the operating system state for a new job.
 */
void INIT()
{
    // Clear main memory
    for (int i = 0; i < 100; i++)
    {
        for (int j = 0; j < 4; j++)
        {
            M[i][j] = '*';
        }
    }

    // Clear CPU registers
    for (int i = 0; i < 4; i++)
    {
        R[i] = '*';
        IR[i] = '*';
    }

    // Reset CPU state
    IC = 0;
    C = 0;
    SI = 0;

    // Reset pointer
    m = 0;
}

/**
 * Reads one data card from the input file into memory.
 */
void READ() {}

/**
 * Writes one memory block to the output file.
 */
void WRITE() {}

/**
 * Terminates the currently executing user program.
 */
void TERMINATE() {}

/**
 * Handles supervisor service requests generated by the user program.
 */
void MOS()
{
    if (SI == 1)
        READ();
    else if (SI == 2)
        WRITE();
    else
        TERMINATE();
}

/**
 * Computes the memory address specified in the current instruction.
 */
int location()
{
    return (IR[2] - '0') * 10 + (IR[3] - '0');
}

/**
 * Executes the loaded user program instruction by instruction.
 */
void EXECUTEUSERPROGRAM()
{
    while (true)
    {
        // Fetch the next instruction from memory.
        for (int i = 0; i < 4; i++)
            IR[i] = M[IC][i];
        IC++;

        // Increment the execution time counter.
        TTL++;

        // Decode and execute the fetched instruction.
        switch (IR[0])
        {
        case 'G':
            SI = 1;
            MOS();
            break;

        case 'P':
            SI = 2;
            MOS();
            break;

        case 'H':
            SI = 3;
            MOS();
            return;

        case 'L':
            for (int i = 0; i < 4; i++)
                R[i] = M[location()][i];
            break;

        case 'S':
            for (int i = 0; i < 4; i++)
                M[location()][i] = R[i];
            break;

        case 'C':
            C = 1;
            for (int i = 0; i < 4; i++)
                if (R[i] != M[location()][i])
                {
                    C = 0;
                    break;
                }
            break;

        case 'B':
            if (C == 1)
                IC = location();
            break;

        case 'N':
        {
            for (int i = 0; i < 4; i++)
                R[i] = (R[i] == '1' && M[location()][i] == '1') ? '1' : '0';
            break;
        }

        case 'O':
        {
            for (int i = 0; i < 4; i++)
                R[i] = (R[i] == '1' || M[location()][i] == '1') ? '1' : '0';
            break;
        }

        case 'X':
        {
            for (int i = 0; i < 4; i++)
                R[i] = (R[i] != M[location()][i]) ? '1' : '0';
            break;
        }
        default:
            cout << "\nOpcode Error. Program ended abnormally.\n";
            return;
        }
    }
}

/**
 * Starts execution of the loaded user program.
 */
void STARTEXECUTION()
{
    IC = 0;
    EXECUTEUSERPROGRAM();
}

/**
 * Loads the input job into memory
 */
void LOAD()
{
    fin.open("input.txt");
    fout.open("output.txt");

    m = 0;

    while (fin.getline(buffer, 41))
    {
        if (buffer[0] == '$')
        {
            switch (buffer[1])
            {
            case 'A':
            {
                INIT(); // Start of a new job
                break;
            }
            case 'D':
            {
                STARTEXECUTION(); // Execute after all program cards are loaded
                break;
            }
            case 'E':
            {
                fout << endl
                     << endl; // Separate outputs of different jobs
                break;
            }
            }
        }
        else
        {
            // Load one program card into memory
            int k = 0;
            while (buffer[k])
            {
                for (int i = 0; i < 4; i++)
                {
                    M[m][i] = buffer[k] ? buffer[k++] : '*';
                }
                m++;
            }
        }
    }
    fin.close();
    fout.close();
}
int main()
{
    LOAD();
    return 0;
}